export const C = {
  bg:         "#f3f2ef",
  card:       "#ffffff",
  border:     "#e0ddd8",
  primary:    "#0a66c2",
  primaryHov: "#004182",
  text:       "#191919",
  sub:        "#666666",
  muted:      "#999999",
  tileBase:   "#ffffff",
  tileHov:    "#e8f0fb",
  tileSel:    "#cce0ff",
  tileGoal:   "#d4f4e2",
  accent:     "#057642",
  warn:       "#b74700",
  shadow:     "0 2px 8px rgba(0,0,0,0.10)",
  shadowLg:   "0 4px 20px rgba(0,0,0,0.13)",
};

export const s = {
  app: {
    minHeight: "100vh",
    background: C.bg,
    fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
    color: C.text,
    display: "flex",
    flexDirection: "column",
  },
  nav: {
    background: C.card,
    borderBottom: `1px solid ${C.border}`,
    padding: "0 24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: 56,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    position: "sticky",
    top: 0,
    zIndex: 10,
  },
  navLogo: {
    fontSize: 20,
    fontWeight: 700,
    color: C.primary,
    letterSpacing: "-0.3px",
    cursor: "pointer",
    userSelect: "none",
  },
  navLinks: { display: "flex", gap: 4 },
  navBtn: (active) => ({
    background: active ? "#e8f0fb" : "none",
    border: "none",
    cursor: "pointer",
    padding: "6px 14px",
    borderRadius: 20,
    fontSize: 14,
    fontWeight: active ? 600 : 400,
    color: active ? C.primary : C.sub,
    transition: "all 0.15s",
  }),
  page: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "32px 16px 64px",
  },
  card: {
    background: C.card,
    borderRadius: 12,
    border: `1px solid ${C.border}`,
    boxShadow: "0 2px 8px rgba(0,0,0,0.10)",
    padding: 32,
    width: "100%",
    maxWidth: 480,
  },
  h1: { fontSize: 28, fontWeight: 700, margin: "0 0 6px", color: C.text },
  h2: { fontSize: 20, fontWeight: 700, margin: "0 0 12px", color: C.text },
  p: { fontSize: 15, color: C.sub, lineHeight: 1.6, margin: "0 0 16px" },
  btn: (variant = "primary") => ({
    background: variant === "primary" ? C.primary : "transparent",
    color: variant === "primary" ? "#fff" : C.primary,
    border: variant === "primary" ? "none" : `1.5px solid ${C.primary}`,
    borderRadius: 24,
    padding: "10px 28px",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.15s",
    boxShadow: variant === "primary" ? "0 2px 6px rgba(10,102,194,0.18)" : "none",
  }),
  chip: (color) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    background:
      color === "green" ? "#e6f4ea" :
      color === "blue"  ? "#e8f0fb" : "#fff3e0",
    color:
      color === "green" ? C.accent :
      color === "blue"  ? C.primary : C.warn,
    border: `1px solid ${
      color === "green" ? "#a8d5b5" :
      color === "blue"  ? "#b0cef0" : "#f4c28a"
    }`,
    borderRadius: 20,
    padding: "4px 12px",
    fontSize: 13,
    fontWeight: 600,
  }),
};